force-app/main/default/objects/Configured_Object__c/Configured_Object__c.object-meta.xml
<CustomObject>
    <label>Configured Object</label>
    <nameField>
        <label>Objects Configured Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configured Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configured_Object__c/fields/Activate__c.field-meta.xml
<CustomField>
    <fullName>Activate__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used to activate and deactivate the button generated in the Layout of the object.</description>
    <label>Activate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Configured_Object__c/fields/Layout__c.field-meta.xml
<CustomField>
    <fullName>Layout__c</fullName>
    <description>Used to inform which layout the button will be included in.</description>
    <label>Layout</label>
    <length>52</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configured_Object__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>Object to define the button.</description>
    <label>Object</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configured_Object__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <description>Field to store LWC name.</description>
    <label>Template</label>
    <length>32</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControllerSetupObjects.cls
public with sharing class ControllerSetupObjects {

    @AuraEnabled
    public static List<Configured_Object__c> getAllRecords(){
        try {
            return [SELECT Id, Layout__c, Activate__c, Name, Object__c, Template__c, Template__r.Name, LastModifiedDate, CreatedDate FROM Configured_Object__c];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void deleteConfiguration(String recordId){
        try {
            Database.delete([SELECT Id FROM Configured_Object__c WHERE Id = :recordId LIMIT 1]);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}